FROM node:22-alpine

WORKDIR /app/backend

COPY backend/package*.json ./
COPY backend/tsconfig.json ./
COPY backend/prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY backend/src ./src
COPY backend/. .

CMD ["npm", "run", "go"]