FROM node:22-alpine

WORKDIR /app

COPY ./package*.json ./
COPY ./tsconfig.json ./
COPY ./prisma ./prisma

RUN npm install
RUN npx prisma generate

COPY ./src ./src
COPY ./. .

CMD ["npm", "run", "go"]