services:
  quiz-backend:
    build:
      context: ../
      dockerfile: dockerfile
    env_file:
      - .env
      - .env.prod
    ports:
      - '${PORT}:${PORT}'
    networks: [app-network]

networks:
  app-network:
    external: true
    name: quiz-builder
